### ISSUE TITLE
bot.whisper mismatched variables

### ISSUE THREAD

**Issue by z-gnu** [martmists/asynctwitch#13]
bot.whisper is passed message, but uses msg

corrected: 
def whisper(self, user, message):
        """
        Send a private message to a user
        
        Parameters
        ----------
        user : :class:`User`
            The user to send a message to.
        message : str
            The message to send.
        """
        yield from self._send_privmsg(user.channel, ".w {} {}".format(user.name, message))

**Comment by Martmists-GH** [comment]
Fixed in rewrite
