### ISSUE TITLE
play_song call blocking event loop

### ISSUE THREAD

**Issue by Martmists-GH** [martmists/asynctwitch#2]
idk how to fix this

**Comment by bibby** [comment]
`await p.wait()` is where you're blocking. It continues on after the subprocess has terminated.

Ideally, you'd want to save the subprocess pid to kill later with a `stop` or `skip` command.

**Comment by Martmists-GH** [comment]
The problem is that when I try to use ffplay it blocks any input, killing the PID won't change that

**Comment by Martmists-GH** [comment]
Is there a way to get the length of the audio file without external
libraries and then sleep that amount of time?

**Comment by Martmists-GH** [comment]
fixed as of fb38e87d59967cf7a0003757f16207c94990063a
