### ISSUE TITLE
Multiple channels.

### ISSUE THREAD

**Issue by ConnorBP** [martmists/asynctwitch#8]
Could a multiple channel connections be implemented into this library? It would be nice to say use a list instead of a string variable for the channels and have the bot automatically work in each channel. Would it be more efficient than running a new instance of the bot for each channel or am i better off just making a new bot object for each channel i would like to connect to?

**Comment by Martmists-GH** [comment]
take a look at the changes I made in 906652dc3f989763e923a3461500a16d06bb9aee. If you know a better way to implement this, feel free to make a PR

**Comment by Martmists-GH** [comment]
Closing this as of 906652dc3f989763e923a3461500a16d06bb9aee
