### ISSUE TITLE
bot.say not working

### ISSUE THREAD

**Issue by ConnorBP** [martmists/asynctwitch#9]
After the latest patch my commands have stopped working. I have been trying to debug why but i do not know your code so it is hard to do. This is what i have gathered so far however: 

- The bot is definitely still receiving the commands. I put a little print in my command to check that it is running. It is therefor the bot.say which is not returning anything. 

- It did work before the update. I also tried reducing the amount of channels in my list to 1. Still the same. Tried using a simple string variable for the channel to use the system that only uses one channel, same thing happened. 

My best guess is that somewhere along the way the channel the message is supposed to send to gets lost. Could also be a variable type missmatch or a simple typo.

**Comment by Martmists-GH** [comment]
Oh right completely forgot!

Bot.say uses self.channel, I need to rework it to use a channel specified by the user. Noted and I'll fix it asap

**Comment by Martmists-GH** [comment]
Latest commit should have fixed this
